---
title: "Project Report"
author: "Samantha J. Poteet and Tavio Pela"
date: "2022-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Analytics Term Project

## Project Description

### Topic:

Risk and effects of flooding in the US

### Why it Matters:

Risk of flooding puts communities in danger of numerous short- and long-term consequences. Entire communities can be uprooted as their homes are destroyed. Flooding can cause fatalities, property damage, and disease by carrying sewage and toxic runoff, polluting drinking water supplies, and leaving bacteria and mold that contribute to respiratory illnesses in their wake. Flood risks are expected to continue to increase as global climate change contributes to heavier precipitation, more frequent hurricanes, and higher sea levels.

### Description of Datasets


#### - Race_and_Income

The Race_and_Income datasets contain information about both racial composition and median household income for 2020 at the county, census tract, and block group level.

These datasets were made by combining sections of two tables from the IPUMS National Historical Geographic Information System (IPUMS NHGIS, University of Minnesota, www.nhgis.org). We make use of Table B03002 and Table B19013. Both use data from the 2020 American Community Survey available at the county, census tract, and block group level.

Table B03002 displays estimates of population demographics categorized via Hispanic or Latino origin by race (example categories include Not Hispanic or Latino: White alone, Not Hispanic or Latino: Two or more races, Hispanic or Latino: White alone, etc.).

Table B19013 displays median household income in the past 12 months (relative to the 2020 survey period) in 2020 inflation-adjusted dollars.


#### - NFHL

Access to the National Flood Hazard Layer (NFHL) is provided by the Federal Emergency Management Agency (FEMA) (FEMA Map Service Center - National Flood Hazard Layer (NFHL) Database Search). In this dataset there are 32 layers, some include: flood hazard zones and labels, flood insurance rate map, hydraulic and flood control structures, coastal barrier resource systems and otherwise protected areas, and Limit of Moderate Wave Action (LiMWA).

For our purposes we are concerned with the zoning layers and the flood control structures. The data set is the most current and updated in 2022. This dataset spatially covers over 90 percent of the United States.


#### - How are they Related?

The NFHL observations contain identifying codes that can be used to merge it with the Race_and_Income data by census tract so that we can investigate flood hazard zone demographics.

## Data Processing


### Overview

In our project, we develop a methodology for using the Race/Income and NHFL data that should allow for tract-level analysis of any county in the US for which the data is not missing. Running our analysis across the whole of the US (or even the whole of one state at once) is possible in theory, but the computational time required to produce our results/visuals is too large given the volume of data required, so we choose narrow our focus to Broward County, FL as a test case.

*[[WHY FL???  WHY SPECIFICALLY BROWARD COUNTY, FL????]]* ------------------------------
{{here are some of my thoughts, but pls add to it and put 'em in a coherent format}}
 - FL b/c coastal so flooding is a very real possibility there
 - Broward b/c most diverse county in FL; if we want to analyze impacts across demographics, need place with sufficient demographic diversity to observe differences ----------------------------------------

### Race/Income Data

Our tract-level data on racial demographics includes many different categories, which we simplify for the purposes of our analysis. In our analysis, we use "White" to refer to those reported as "Not Hispanic or Latino: White alone", "Black" to refer to those reported as "Not Hispanic or Latino: Black or African American alone", "Native" to refer to those reported as "Not Hispanic or Latino: American Indian and Alaska Native alone", "Asian" to refer to those reported as "Not Hispanic or Latino: Asian alone", "Hispanic" to refer to those reported as "Hispanic or Latino", and "Other" to refer to those in all other Not Hispanic or Latino categories (e.g., "Not Hispanic or Latino: Some other race alone", "Not Hispanic or Latino: Two or more races", etc.).

While this is an oversimplification of race and ethnicity in the United States (in particular because it does not draw distinctions between, say "Hispanic or Latino: White alone", "Hispanic or Latino: Black or African American alone", and "Hispanic or Latino: Two or more races"), we used these categories as a way of approximating broad trends in population distributions.

We have no extreme values in this data to deal with, but we are missing data for two tracts in our county of focus. *[[DO WE KNOW WHY??? WASN'T ONE OF THOSE THAT BIG RESERVE AREA???]]* On our maps, these areas are grayed out to show in which reasons we were missing data. The validity of the portion for which our analysis relies upon estimates made from the data is caveated as being valid only for the nonmissing sample.

We transform this data in a few ways for some of our visualizations.

For our bar plot of the demographics of Broward County, we use the racial categories described above and compute the sum of the population observed in each category across all tracts, as well as the total county population.  We then divide the totals for each racial group by the total county population and multiply by 100 to get the percentage of the county population made up by each group.

For our map of tracts by largest ethnic group, we create a variable identifying the largest racial group in each given tract. We then subset the original dataframe so that all tracts with the same dominant racial group are each in their own dataframe.  We then calculate what percentage of the total population of each tract the dominant group in that tract makes up.

Finally, for our analysis of racial disparities in risk exposure to flooding, we first make a simplifying assumption that *within* tracts, population is dispersed evenly and there are no racial disparities in risk-exposure.  The effect of this assumption will likely be to bias us against finding disproportionate impacts.  Combining our Race/Income data with our NHFL data and reprojecting it to a projection that conserves area, we calculate the proportion of each tract's total area that is covered by each kind of flood zone. We then use our simplifying assumption to estimate the number of people in each category affected by each kind of flood zone.  We then separate "VE" and "AE" flood zones as our "high risk" areas *[[WHY THESE TWO?? WHAT DO THEY MEAN?]]*.  Finally, we compute what percent of the highest-risk population each group makes up by dividing the sum of the estimated affected population of that group by the sum of the total estimated affected population.


### NHFL Data
---------------------------------
INSTRUCTIONS:  *[[[WHEN DONE, DELETE THIS INSTRUCTIONS SECTION]]]*

Explain how you processed your data and why you made the choices you did. Identify the unit of analysis in your cleaned, merged dataset.

Explain any transformations you applied, how you dealt with any missing data or extreme values, and why.
---------------------------------



[[HOW DEALT WITH MISSING AND/OR EXTREME VALUES]]

[[HOW DO WE TRANSFORM THE NHFL DATA TO GET WHAT WE NEED FOR THE HAZARDS?  WHY DO WE MAKE THE 'RISK' LEVEL IDENTIFICATION CHOICES WE DO?]]
 - I assume the projection should be brought up



## Findings


[[Basically, seems like white ppl are disproportionately at risk of flooding in this specific county because they tend to live on the coast; we get the disproportionate risk by comparing the two bar graphs, and the coastal-living explanation by comparing the hazard layer map to the demographics map; limitations to our estimates exist because of the simplifying assumption I describe in data processing... it may be that within the tracts themselves there are racial disparaties due to differences in location and housing quality]]





